---
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew install gnu-tar
      script: make test
    - os: linux
      sudo: false
      addons:
        apt:
          packages: devscripts
      script: debuild -uc -us
    - os: linux
      dist: trusty
      sudo: false
      group: beta
      script: debuild -uc -us
