---
language: minimal
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew install gnu-tar
        - brew install moreutils
        - brew install shellcheck
        - brew install jq
        - brew install pigz
      script: make test
    - os: linux
      dist: trusty
      sudo: required
      install:
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-v0.4.7.linux.x86_64.tar.xz"
        - tar --xz -xvf "shellcheck-v0.4.7.linux.x86_64.tar.xz"
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - moreutils
            - fakeroot
            - jq
            - pigz
      script: debuild -uc -us
